### ISSUE TITLE
Improve the `overwrite` flag on fields

### ISSUE THREAD

**Issue by verkaufer** [1Password/ansible-onepasswordconnect-collection#10]
The `overwrite` flag can be confusing and may lead to accidental data loss when used without care. We can clarify how field overwrites work by using more descriptive switch values instead of `always` and `never`.

This issue tracks proposals and discussion around improving this user experience.

**Comment by maximevalette** [comment]
Upvoted. Just spent two hours trying to make `overwrite: no` work but it keeps overwriting the item fields. Not very safe indeed.

**Comment by verkaufer** [comment]
Thanks for the feedback @maximevalette ! This issue is related to #11  . Originally we were trying to avoid regenerating on subsequent playbook executions.

Thinking more about how Ansible playbooks define the state of a system _after_ executing the roles through idempotency, would you expect the behavior to be:

- I define an item as a part of a playbook role
- I set `state: present` or `state: absent` for each item
  - If I define `state: present`, the values defined in the role should match the values stored in 1Password after running the playbook
  - Any values I change in 1Password outside of the playbook execution are overwritten

Let me know what you think - this is an issue I'm hoping to get fixed soon.

**Comment by maximevalette** [comment]
Thanks for your answer! I think that's would be the best behavior giving how Ansible is working with roles and data. As you mentioned in your guide my Secrets vault is only accessed by Ansible roles and therefore should not be updated by a human.

Regarding the issue #11 I agree that would also be the best behavior and should be updated as well as this one.

**Comment by verkaufer** [comment]
This will be resolved in the next major release. The changes are not backwards compatible, so unfortunately we need to do a v2 release.

**Comment by maximevalette** [comment]
Great news! Thanks for this update :)
