### ISSUE TITLE
Fix `field_purpose` assignment 

### ISSUE THREAD

**Issue by verkaufer** [1Password/ansible-onepasswordconnect-collection#20]
### Your environment

Collection Version: 2.0.0

Connect Server Version: latest

OS: MacOS 10.15.7

Ansible Version: 2.10

## What happened?

The `field_purpose` will never be assigned because the comparison is checking lowercase values against uppercase values.

## What did you expect to happen?

`field_purpose` would be assigned correctly when the item is one of the corresponding item categories.

## Steps to reproduce
1. Use the example playbook from the README. The item category defaults to `password`
2. Add a field with type `concealed`

**Comment by verkaufer** [comment]
While correcting this issue I learned that the item type `LOGIN` and `PASSWORD` have required fields that we were not communicating to customers. Instead of defaulting to the `LOGIN` item type, we'll use `API_CREDENTIAL` going forward.

🔥  This will impact existing items defined in a playbook if the items do not have a `category` value. This means a `login` field may turn into an `api_credentials` field if a customer updates to the latest collection version and continues to use the default value for an item `category`.

**Comment by SimonBarendse** [comment]
> That said, changing an item type from `login` to `api_credential` will not cause data loss.

I believe changing the item type cannot be done in place, so we are forcing new resources (delete and create new ones) is that correct?

If so, what is the impact on things like item history?
