### ISSUE TITLE
unexpected results for item_info with field parameter

### ISSUE THREAD

**Issue by rembart** [1Password/ansible-onepasswordconnect-collection#34]
Hello,

I noticed some unexpected behaviour while using the field argument on the item_info module

Here is an example:

![image](https://user-images.githubusercontent.com/3373129/128549597-adab231e-9031-49cc-9622-33d6275c6285.png)

1. Query for the field 'web-username'
instead of getting the query result of the field 'web-username' in the op_item dict like { value: 'test-username-web', ... } its in the 'field' attribute - not sure if this is intended 

  tasks:
    - name: 1-Query web-username
      item_info:
        item: TEST-App-1
        vault: my-vault-id
        field: web-username
      no_log: true
      register: debug_one

    - name: Print the result
      ansible.builtin.debug:
        var: debug_one

TASK [Print the result] **********************************************************************************************************************************************************************************************
ok: [localhost] => {
    "debug_one": {
        "changed": false,
        "failed": false,
        "field": "test-username-web",
        "op_item": {}
    }
}

2. Query for a field that exists multiple times within different sections -> only one match is returned, again value is in the field attribute

3. Query the whole item without field, only one username/password is return in the result array - from different sections, i guess this happens during the api -> python transformation where the keys are overwritten.

 tasks:
    - name: 3-Query item
      item_info:
        item: TEST-App-1
        vault: my-vault-id
      no_log: true
      register: debug_item

    - name: Print the result
      ansible.builtin.debug:
        var: debug_item
       
ok: [localhost] => {
    "debug_item": {
        "changed": false,
        "failed": false,
        "op_item": {
            "category": "LOGIN",
            "createdAt": "2021-08-06T17:05:39Z",
            "fields": {
                "notesPlain": {
                    "id": "notesPlain",
                    "label": "notesPlain",
                    "purpose": "NOTES",
                    "type": "STRING"
                },
                "password": {
                    "id": "91F5FD24A0....",
                    "label": "password",
                    "section": {
                        "id": "Section_5A00EF772...."
                    },
                    "type": "CONCEALED",
                    "value": "test-password-web"
                },
                "username": {
                    "id": "5135F336F4....",
                    "label": "username",
                    "section": {
                        "id": "Section_1E8738FADA...."
                    },
                    "type": "STRING",
                    "value": "test-username-haproxy"
                },
                "web-username": {
                    "id": "889126C76....",
                    "label": "web-username",
                    "section": {
                        "id": "Section_5A00EF772966...."
                    },
                    "type": "STRING",
                    "value": "test-username-web"
                }
            },
            "id": "fpdo7wrajn....",
            "lastEditedBy": "FKJ36NA3CVC....",
            "sections": [
                {
                    "id": "linked items",
                    "label": "Related Items"
                },
                {
                    "id": "Section_5A00EF772....",
                    "label": "Web interface"
                },
                {
                    "id": "Section_1E8738FADA.....",
                    "label": "haproxy"
                },
                {
                    "id": "Section_5A00EF772966.....",
                    "label": "mysql"
                }
            ],
            "title": "TEST-App-1",
            "updatedAt": "2021-08-06T17:16:14Z",
            "vault": {
                "id": "my-vault-id"
            },
            "version": 4
        }
    }
}

Furthermore specifying a section for field lookups (to get a specific 'in-item-namespace') is currently not possible. This is a blocker to migrate our main workloads to the 1password connect server since our old entries are organised by sections.

We would be happy to commit a pull request regarding this issues, but we are currently not sure how the intended behaviour  for this module should be. I guess returning all results in op_item as array for field searches, or ignore results from sections and add a dedicated section parameter would be possible. 

Best Klaus

**Comment by rembart** [comment]
I guess a dedicated module eg. field_value would be the best approach to have the same behaviour as the existing onepassword ansible lookup (the one which is based on the op cli client)

field_value:
  vault: 
  item: 
  section: (optional, if not set -> ignore fields nested in sections)
  field: 
 
It is still possible that a field-label occurs multiple times within a section, but as soon as the result set has multiple or no matches/candidates, the module should fail hard. In my opinion it's better to get an error during the run than working with wrong values in downstream tasks.

best Klaus

**Comment by verkaufer** [comment]
Hey @rembart ! Thanks for filing this issue.

re: (1) You're right, this is inconsistent and I'll have someone on the team take a look at making it consistent with our `op-item` convention.

re: (2) & (3) Great catch. I think we need to re-evaluate how we handle the mapping for this case.

I like your suggestion to raise an error if the result has multiple matches. For the case where a field with the same name exists in multiple sections, would you always expect an error? Or would it be helpful if there was some kind of namespacing for the results. E.g. the dict key for the field could be `op_item["<section>/<field_name>"]`

**Comment by rembart** [comment]
Hello @verkaufer, thanks for taking care about this issue!

ad 2/3
I guess the best behaviour, for automated workflows, would be something like this

> item/example-1.domain.com 
> username: xyz-0
> section-1/username: xzy-1
> section-2/username: xyz-2
> item/example-1.domain.com 
> username: xyz-0
> section-1/username: xzy-1
> section-2/username: xyz-2

> item/example-2.domain.com 
> username: abc-0
> section-1/username: abc-1
> section-2/username: abc-2
> section-3/username: abc-3a
> section-3/username: abc-3b

item: example-1.domain.com 
field: username

**Comment by verkaufer** [comment]
Thanks for the examples! I'll see what we can be done about making this more intuitive (and correct). Appreciate your report and your patience.

**Comment by verkaufer** [comment]
Update on this issue - I'm aiming to have a PR open in the next week with a new `field_info` module. It should solve your issues with the collection not handling non-unique field names :) 

Thanks for your patience - we're stretched a little thin right now working on a bundle of other features.
