### ISSUE TITLE
Ansible 6.0.0 compatibility

### ISSUE THREAD

**Issue by toonvd** [1Password/ansible-onepasswordconnect-collection#57]
### Your environment

Collection Version: `onepassword.connect 2.2.0`

Connect Server Version: latest

OS: Mac - latest

Ansible Version: 6.0.0

## What happened?
I got 400s when trying to create a new item:

## What did you expect to happen?
A new Item was created

## Steps to reproduce
1. Upgrade to 6.0.0
2. Try to create a new item - doesn't work
3. Downgrade to 5.80
4. Try to create a new item - works

## Notes & Logs
```
{"log_message":"(I) GET /v1/vaults/xxxxx/items/xxxxcompleted (400: Bad Request)","timestamp":"2022-06-22T13:48:34.338606891Z","level":3,"scope":{"request_id":"xxxxx","jti":"xxxxxx"}}
```

**Comment by volodymyrZotov** [comment]
Fixed in [ansible-onepasswordconnect-collection v2.1.1](https://github.com/1Password/ansible-onepasswordconnect-collection/releases/tag/v2.2.1)
